nginx:
  image: nginx:1.9.6
  restart: always
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./www-content:/usr/share/nginx/html
  environment:
    - VIRTUAL_HOST=home.jrw.fi
    - LETSENCRYPT_HOST=home.jrw.fi
    - LETSENCRYPT_EMAIL=jarno@jrw.fi
